const DEFAULTS={gptUrl:"",gptIdeasUrl:"",gptScriptUrl:"",gptPromptsUrl:"",gptAnalystUrl:"",gptRefinerUrl:"",gptGeneratorUrl:"",gptFallbackUrl:"",gptThumbUrl:"",gptYoutubeUrl:"",appOrigin:"https://roteiro-mu.vercel.app",openMode:"reuse",cleanerEnabled:false,cleanerHour:"22:00",cleanerDryRun:true};
const GPT_FIELDS=["gptIdeasUrl","gptScriptUrl","gptPromptsUrl","gptAnalystUrl","gptRefinerUrl","gptGeneratorUrl","gptFallbackUrl","gptThumbUrl","gptYoutubeUrl"];
async function load(){const c=await chrome.storage.sync.get(DEFAULTS);for(const id of GPT_FIELDS)document.getElementById(id).value=c[id]||"";gptIdeasUrl.value=c.gptIdeasUrl||c.gptUrl||"";appOrigin.value=c.appOrigin||DEFAULTS.appOrigin;openMode.value=c.openMode||"reuse";cleanerEnabled.checked=!!c.cleanerEnabled;cleanerHour.value=c.cleanerHour||"22:00";cleanerDryRun.checked=c.cleanerDryRun!==false;}
async function save(showStatus=true){const urls=Object.fromEntries(GPT_FIELDS.map(id=>[id,document.getElementById(id).value.trim()]));const a=appOrigin.value.trim().replace(/\/+$/,""),m=openMode.value;for(const u of Object.values(urls)){if(u&&!u.startsWith("https://chatgpt.com/")){alert("Todas as URLs dos GPTs devem começar com https://chatgpt.com/");return false;}}await chrome.storage.sync.set({...urls,gptUrl:urls.gptIdeasUrl,appOrigin:a,openMode:m,cleanerEnabled:cleanerEnabled.checked,cleanerHour:cleanerHour.value||"22:00",cleanerDryRun:cleanerDryRun.checked});await chrome.runtime.sendMessage({type:"CORVO_CLEANER_RESCHEDULE"}).catch(()=>{});if(showStatus){saved.textContent="Salvo ✓";setTimeout(()=>saved.textContent="",1800);}return true;}
async function runNow(){if(!cleanerDryRun.checked&&!confirm("A exclusão real é permanente. Excluir agora somente as conversas concluídas registradas como criadas pelo Corvo Bridge?"))return;if(!await save(false))return;cleanerResult.textContent="Executando...";const r=await chrome.runtime.sendMessage({type:"CORVO_CLEANER_RUN_NOW"});if(!r?.ok&&r?.error){cleanerResult.textContent=`Erro: ${r.error}`;return;}cleanerResult.textContent=r.stopped?"Limpeza parada.":(r.dryRun?`Teste: ${r.candidates||0} candidatas próprias`:`Excluídas: ${r.deleted||0} • Já removidas: ${r.alreadyMissing||0} • Falhas: ${r.failed||0}`);await syncCleanerButtons();}
async function refreshList(){cleanerResult.textContent="Atualizando lista...";refreshCleaner.disabled=true;const r=await chrome.runtime.sendMessage({type:"CORVO_CLEANER_REFRESH_LIST"});if(!r?.ok&&!r?.stopped){cleanerResult.textContent=`Erro: ${r?.error||"falha"}`;}else cleanerResult.textContent=r?.stopped?"Atualização parada.":`Disponíveis: ${r.available||0} • Removidas manualmente: ${r.removed||0} • Indeterminadas: ${r.unknown||0}`;await syncCleanerButtons();}
async function stopNow(){stopCleaner.disabled=true;cleanerResult.textContent="Parando limpeza...";const r=await chrome.runtime.sendMessage({type:"CORVO_CLEANER_STOP"});cleanerResult.textContent=r?.ok?"Parada solicitada.":`Erro: ${r?.error||"falha"}`;setTimeout(syncCleanerButtons,300);}
async function syncCleanerButtons(){const c=await chrome.runtime.sendMessage({type:"CORVO_CLEANER_GET_STATE"}).catch(()=>null);const busy=Boolean(c?.status?.running||c?.refreshStatus?.running||c?.runtimeBusy);runCleaner.disabled=busy;refreshCleaner.disabled=busy;stopCleaner.disabled=!busy;stopCleaner.textContent=(c?.status?.stopping||c?.refreshStatus?.stopping)?"Parando...":"Parar limpeza";}
document.querySelector("#save").addEventListener("click",save);document.querySelector("#runCleaner").addEventListener("click",runNow);document.querySelector("#refreshCleaner").addEventListener("click",refreshList);document.querySelector("#stopCleaner").addEventListener("click",stopNow);load();syncCleanerButtons();setInterval(syncCleanerButtons,1000);
